### ISSUE TITLE
case records - Drag and Drop functionality and styling issues

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#100]
From user feedback
>Drag and drop is working for Case Files, but not for Final Letter. Also, we are not able to save the files whether you drag and drop or use the Upload button. After uploading files, we click the Save button and then return to the Workbench. When you reopen the same case, the uploaded files are no longer there.

**Comment by HansVraga** [comment]
From user feedback:
>In addition, we are unable to open a file once it is uploaded or dropped into the case record.

**Comment by HansVraga** [comment]
From user feedback:
>Teresa Fish (who was using Firefox) was unable to drag and drop more than two files. The third file she tried to drag and drop opened instead. This did not happen for a staff member using Chrome.

**Comment by HansVraga** [comment]
From user feedback:
>When the Final Letter is uploaded, Teresa Fish is unable to see the entire title of the document in the cell (using Firefox), and it also seems like either the last few letters of the file name were changed, or a few letters were added at the end (i.e., MBs – what does this mean?).

**Comment by HansVraga** [comment]
From user feedback
>The case files that are uploaded to the record seem to take up a lot of space on the UI because they go to multiple lines instead of remaining on one line (there is plenty of space to keep most on a single line.

**Comment by HansVraga** [comment]
@mitch-wim made the styling adjustments.

**Comment by aaronstephenson** [comment]
From user feedback:
>o	NOT FIXED for final letter. We are unable to drag and drop files into Final Letter. When using Upload button for Final Letter, the file title appears, but you are unable to save it. 
>o	Drag and drop and upload button work.  They can be downloaded but not deleted.  We need to be able to delete uploaded files (e.g. to remove the 1st draft of the final letter)

**Comment by aaronstephenson** [comment]
@mitch-wim could you fix the final letter drag and drop functionality? It should appear (and work) when case status = Awaiting Final Letter or Awaiting Level 2 QC.

**Comment by mitch-wim** [comment]
I changed some styling - I realized the expanded drop zone won't work. There are two file dropzones, so you can't expand one without making the other unreachable... and you can't do it by hovering over the specific dropzone either, because you basically have to hover over/past one to get to the other... So I disabled the expanded dropzone

As far as it not even working, it's giving an error when dragging a file into the Final Letter upload spot... 
`ION: Error in ./WorkbenchDetailComponent class WorkbenchDetailComponent - inline template:195:24 caused by: Cannot read property '0' of undefined`

I figured that's something you might be better at handling @aaronstephenson.

**Comment by aaronstephenson** [comment]
@mitch-wim yup, that error was caused by my not casting the FileList to an Array, oops.  Just for the sake of you being able to continue your work without waiting for a git merge, go ahead and change line 956 in your local copy of workbench-detail.component.ts to this:
`this._finalletterToUpload = <Array<File>> fileInput.target.files[0] || fileInput.dataTransfer.files[0];`

**Comment by HansVraga** [comment]
@mitch-wim this one might not be finished yet - for a NEW case, is the newest drag&drop functionality you've put together (for case final letter and file upload sections) available?

**Comment by aaronstephenson** [comment]
@mitch-wim did you do this for the New Case situation too?

**Comment by aaronstephenson** [comment]
@mitch-wim could you submit a pull request for this and #122 ?
