### ISSUE TITLE
File Upload broken on QA environment

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#119]
(see picture below) - 
From there I Save, go to workbench, and back to the case and no files
![image](https://cloud.githubusercontent.com/assets/12058013/24063142/d08ef5f0-0b34-11e7-8f56-32d6e71b176e.png)

**Comment by aaronstephenson** [comment]
Fixed this. The case upload function was never getting triggered because I had it checking only when the form was "dirty"... but since the case files part aren't actually in the form (from Angular's perspective), the form was still pristine if you only tried to upload a file but didn't alter any other fields. So I moved the file check outside the form dirty check, and everything seems to work fine now.

**Comment by aaronstephenson** [comment]
Well, it all works in the dev server, but not the QA server. This is because there is no "media" folder in the cbraservices app directory on the QA server. I'll notify Jin that this needs to be created, since I don't have permissions to do so.

**Comment by aaronstephenson** [comment]
Nevermind, fixed this on my own by including the media folder in the cbraservices git repo, so it automatically deploys to the QA server. Case file upload now works end-to-end, everywhere. We will probably want to discuss a better, more permanent location to store these case files, so they aren't deleted when the app code gets updated, and also so they're (potentially) reachable by CBRA staff using tools other than the DMS.
