### ISSUE TITLE
workbench - filter

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/CBRADMS#96]
From testing feedback:
>Clear filter button doesn’t clear the filter it resets it to the default filter.  Rename the button or make it so that it clears all filters including status

**Comment by HansVraga** [comment]
If this does not exist - add a "Default Filter" button that sets the filter to defaults.

**Comment by aaronstephenson** [comment]
Made the button only empty out (clear) all the fields in the filter, rather than emptying them AND re-running the default query. I did not implement a Default button since they didn't really ask for one.

**Comment by aaronstephenson** [comment]
From testing feedback:
> Clear filter now seems to pull up every case in the database (which is slow). Have it return to no records found on the workbench

**Comment by aaronstephenson** [comment]
This was the result of a typo. I had `<button type=""button` instead of `<button type="button" `, which meant the button had no type at all, which made it default to a submit action when clicked. I have corrected this, but only to the originally intended purpose of the button: to clear the filter fields, not to clear the entire case list. If they wish to clear the entire case list, then they can click the Clear button, then click the Search button.
